// Code generated by "stringer -type=Category -trimprefix=Head"; DO NOT EDIT.

package head

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeadTitle-0]
	_ = x[HeadBase-1]
	_ = x[HeadLink-2]
	_ = x[HeadMeta-3]
	_ = x[HeadStyle-4]
	_ = x[HeadScript-5]
	_ = x[HeadNoscript-6]
	_ = x[HeadTemplate-7]
}

const _Category_name = "TitleBaseLinkMetaStyleScriptNoscriptTemplate"

var _Category_index = [...]uint8{0, 5, 9, 13, 17, 22, 28, 36, 44}

func (i Category) String() string {
	if i >= Category(len(_Category_index)-1) {
		return "Category(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
