// Code generated by "stringer -type=CrossOrigin -trimprefix=CrossOrigin"; DO NOT EDIT.

package head

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CrossOriginDefault-0]
	_ = x[CrossOriginAnonymous-1]
	_ = x[CrossOriginUseCredentials-2]
}

const _CrossOrigin_name = "DefaultAnonymousUseCredentials"

var _CrossOrigin_index = [...]uint8{0, 7, 16, 30}

func (i CrossOrigin) String() string {
	if i < 0 || i >= CrossOrigin(len(_CrossOrigin_index)-1) {
		return "CrossOrigin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CrossOrigin_name[_CrossOrigin_index[i]:_CrossOrigin_index[i+1]]
}
