// Code generated by "stringer -type=ReferrerPolicy -trimprefix=ReferrerPolicy"; DO NOT EDIT.

package head

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReferrerPolicyNone-0]
	_ = x[ReferrerPolicyNoReferrer-1]
	_ = x[ReferrerPolicyNoReferrerWhenDowngrade-2]
	_ = x[ReferrerPolicyOrigin-3]
	_ = x[ReferrerPolicyOriginWhenCrossOrigin-4]
	_ = x[ReferrerPolicySameOrigin-5]
	_ = x[ReferrerPolicyStrictOrigin-6]
	_ = x[ReferrerPolicyStrictOriginWhenCrossOrigin-7]
	_ = x[ReferrerPolicyUnsafeURL-8]
}

const _ReferrerPolicy_name = "NoneNoReferrerNoReferrerWhenDowngradeOriginOriginWhenCrossOriginSameOriginStrictOriginStrictOriginWhenCrossOriginUnsafeURL"

var _ReferrerPolicy_index = [...]uint8{0, 4, 14, 37, 43, 64, 74, 86, 113, 122}

func (i ReferrerPolicy) String() string {
	if i < 0 || i >= ReferrerPolicy(len(_ReferrerPolicy_index)-1) {
		return "ReferrerPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReferrerPolicy_name[_ReferrerPolicy_index[i]:_ReferrerPolicy_index[i+1]]
}
