#!/usr/bin/env ruby

tags = File.read("tags").split

f = File.open("autotags.go", "w")

f << "package html\n\n"

f << "import \"github.com/guillermo/lazyview/nodes\"\n\n"

tags.each do  |tag|
  fn = tag.capitalize
  f << "// #{fn} Creates a new #{tag} element\n"
  f << "func #{fn}(options ...interface{}) *nodes.Element {\n"
  f << "  return nodes.NewElement(\"#{tag}\", options...)\n"
  f << "}\n\n"
end

f.close
